### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by BosamiyaSimran** [thosaniparth/Recipe_Recommender#14]
Need to check on code coverage badge as it is still showing 0% after updating test cases

**Comment by thosaniparth** [comment]
Have updated the Badge and tests are running. Currently at 62%. Need to add more tests on Add new Recipes, Vegetarian/Vegan filter and also on calorie count.

**Comment by BosamiyaSimran** [comment]
Have we completed adding all the test cases?

**Comment by thosaniparth** [comment]
Have added some test cases and getting coverage of 68%
