### ISSUE TITLE
[BUG] Login-Home bug 

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/Recipe_Recommender#2]
Added user authorization api and working on UI

_Originally posted by @BosamiyaSimran in https://github.com/thosaniparth/Recipe_Recommender/issues/1#issuecomment-977515411_

A new bug is seen on the existing issue:
When we search recipe on home page, then go to login page and then come back to home page the recipe list is still rendered based on previous search

**Comment by BosamiyaSimran** [comment]
Resolved.
