### ISSUE TITLE
Add a calorie/nutrients tracker.

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/Recipe_Recommender#4]
We could add a calorie count tracker so people might know what calories do the items of the food contains.

**Comment by nsshah14** [comment]
I search an API named Calorie Ninja that would provide us the calorie count of each item in ingredients in the recipe. We can use that to calculate the total calories for the dish.

**Comment by thosaniparth** [comment]
We should use Axios instead of request to fetch the results from api

**Comment by thosaniparth** [comment]
Getting calories but it's a long number, we need to truncate it. Also, we should make sure to put a check of calories should be greater than 0.
