### ISSUE TITLE
Add New Recipes 

### ISSUE THREAD

**Issue by thosaniparth** [thosaniparth/Recipe_Recommender#7]
We should give options to the users to add new recipes so that others can search them and get the information whenever required.

**Comment by BosamiyaSimran** [comment]
I think we should add a form where users can add information so that can be displayed on the screen as it was working earlier

**Comment by thosaniparth** [comment]
I have added the form where it asks the recipe name, ingredients, instructions and time taken to prepare the recipe.

**Comment by thosaniparth** [comment]
I have also added the image URL feature in which users can add the URL of the image to put with the recipe. All details will go to the backend and other users can see the recipe while searching.

**Comment by thosaniparth** [comment]
Completed entire working flow of add new recipes
